name: Issue Template
description: 개발 관련 이슈 사항
title: '[Issue]: '
labels: ['Issue']
body:
  - type: textarea
    id: feature-title
    attributes:
      label: 이슈 내용 요약
      description: 발생한 이슈 내용을 간단하게 요약해주세요.
    validations:
      required: true
  - type: textarea
    id: feature-detail
    attributes:
      label: 이슈 내용 상세 설명
      description: 이슈 발생 시나리오(작업 환경도!), 원인, 시도 방법, 도움이 필요한 포인트 등 상세한 내용을 작성해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 작업 이미지 (UI 작업인 경우 권장)
      description: 작업중인 화면 스크린샷
  - type: textarea
    id: feature-etc
    attributes:
      label: 참고 사항
      description: 프로젝트에 어떤 영향을 미칠지, 참고할 만한 사항이 있다면 작성해주세요.
