name: Feature Development
description: 개발 관련 이슈 사항
title: '[Feature]: '
labels: ['feature']
body:
  - type: textarea
    id: feature-title
    attributes:
      label: 요약
      description: 작업 중인 사항 입력
    validations:
      required: true
  - type: textarea
    id: feature-detail
    attributes:
      label: 기능 관련 상세 설명
      description: 작업 중인 사항에 대한 상세한 설명
    validations:
      required: true
  - type: textarea
    attributes:
      label: 작업 이미지 (UI 작업인 경우 권장)
      description: 작업중인 화면 스크린샷
  - type: textarea
    id: feature-etc
    attributes:
      label: 기타 사항
      description: 기타 관련 정보
